#!/bin/bash

# Silas Bossert, sb2346@cornell.edu
# 06.IX.2017
# Cornell University, Dep. of Entomology, Danforth lab

# This is a helper script for the head_script.sh. There is no need to change it.

set -x

# Function to specify the number of cores on the local machine
corenumber() {
	nproc
}

# Parsing function to specify the used probe set. Specify the exact name here (without paths), e.g.: "hymenoptera.fasta", "lepidoptera.fasta", "arachnida.fasta".
probefile() {
	cd ../
	echo "${PWD##*_}.fasta"
}

# Create output folders for lastz searches. The runs have to be split bc of potential database malfunctions.
mkdir run_1_lastz run_2_lastz run_3_lastz run_4_lastz run_5_lastz run_6_lastz run_7_lastz run_8_lastz run_9_lastz run_10_lastz run_11_lastz run_12_lastz run_13_lastz run_14_lastz run_15_lastz run_16_lastz run_17_lastz run_18_lastz run_19_lastz run_20_lastz

# run 1
phyluce_probe_run_multiple_lastzs_sqlite --db run_1.sqlite --output run_1_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Achipteria_coleoptrata_Chelicerata_Sarcoptiformes_Mite Acromyrmex_echinatior_Hymenoptera Acyrthosiphon_pisum_Homoptera Aedes_aegypti_Diptera Aedes_albopictus_Diptera Aethina_tumida_Coleoptera Agrilus_planipennis_Coleoptera Amphinemura_sulcicollis_Plecoptera Amyelois_transitella_Lepidoptera Anopheles_albimanus_Diptera Anopheles_arabiensis_Diptera Anopheles_atroparvus_Diptera Anopheles_christyi_Diptera Anopheles_coluzzii_Diptera Anopheles_culicifacies_Diptera Anopheles_darlingi_Diptera Anopheles_dirus_Diptera Anopheles_epiroticus_Diptera Anopheles_farauti_Diptera Anopheles_funestus_Diptera 

# run 2
phyluce_probe_run_multiple_lastzs_sqlite --db run_2.sqlite --output run_2_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Anopheles_gambiae_Diptera Anopheles_koliensis_Diptera Anopheles_maculatus_Diptera Anopheles_melas_Diptera Anopheles_merus_Diptera Anopheles_minimus_Diptera Anopheles_nili_Diptera Anopheles_punctulatus_Diptera Anopheles_quadriannulatus_Diptera Anopheles_sinensis_Diptera Anopheles_stephensi_Diptera Anoplophora_glabripennis_Coleoptera Apis_cerana_Hymenoptera Apis_dorsata_Hymenoptera Apis_florea_Hymenoptera Apis_mellifera_Hymenoptera Armadillidium_vulgare_Crustacea_Isopoda Athalia_rosae_Hymenoptera Atta_cephalotes_Hymenoptera Atta_colombica_Hymenoptera Bactrocera_cucurbitae_Diptera Bactrocera_dorsalis_Diptera

# run 3
phyluce_probe_run_multiple_lastzs_sqlite --db run_3.sqlite --output run_3_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Bactrocera_latifrons_Diptera Bactrocera_oleae_Diptera Bactrocera_tryoni_Diptera Baetis_rhodani_Ephemeroptera Belgica_antarctica_Diptera Bemisia_tabaci_Hemiptera Blattella_germanica_Blattodea Bombus_impatiens_Hymenoptera Bombus_terrestris_Hymenoptera Bombyx_mori_Lepidoptera Caligus_rogercresseyi_Crustacea_Maxillopoda Calliphora_vicina_Diptera Calycopis_cecrops_Lepidoptera Camponotus_floridanus_Hymenoptera Catajapyx_aquilonaris_Diplura Centruroides_exilicauda_Chelicerata_Scorpiones Cephus_cinctus_Sarcoptimformes Cerapachys_biroi_Hymenoptera Ceratina_calcarata_Hymenoptera Ceratitis_capitata_Diptera Ceratosolen_solmsi_marchali_Hymenoptera Chaoborus_trivitattus_Diptera Chilo_suppressalis_Lepidoptera Chironomus_riparius_Diptera

# run 4
phyluce_probe_run_multiple_lastzs_sqlite --db run_4.sqlite --output run_4_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Chironomus_tentans_Diptera Cimex_lectularius_Hemiptera Cirrula_hians_Diptera Clogmia_albipunctata_Diptera Clunio_marinus_Diptera Coboldia_fuscipes_Diptera Condylostylus_patibulatus_Diptera Copidosoma_floridanum_Hymenoptera Cotesia_vestalis_Hymenoptera Culex_quinquefasciatus_Diptera Cyphomyrmex_costatus_Hymenoptera Danaus_plexippus_Lepidoptera Daphnia_magna_Crustacaea_Branchiopoda Daphnia_pulex_Crustacaea_Branchiopoda Dendroctonus_ponderosae_Coleoptera Dermatophagoides_farinae_Chelicerata_Acariformes_Mite Dermatophagoides_pteronyssinus_Chelicerata_Acariformes_Mite Diachasma_alloeum_Hymenoptera Diaphorina_citri_Hemiptera Dinoponera_quadriceps_Hymenoptera Diuraphis_noxia_Hemiptera

# run 5
phyluce_probe_run_multiple_lastzs_sqlite --db run_5.sqlite --output run_5_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Drosophila_busckii_Diptera Drosophila_elegans_Diptera Drosophila_erecta_Diptera Drosophila_eugracilis_Diptera Drosophila_ficusphila_Diptera Drosophila_grimshawi_Diptera Drosophila_kikkawai_Diptera Drosophila_melanogaster_Diptera Drosophila_miranda_Diptera Drosophila_mojavensis_Diptera Drosophila_navojoa_Diptera Drosophila_persimilis_Diptera Drosophila_rhopaloa_Diptera Drosophila_sechellia_Diptera Drosophila_simulans_Diptera Drosophila_suzukii_Diptera Drosophila_takahashii_Diptera Drosophila_virilis_Diptera

# run 6
phyluce_probe_run_multiple_lastzs_sqlite --db run_6.sqlite --output run_6_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Glossina_morsitans_Diptera Glossina_pallidipes_Diptera Glossina_palpalis_gambiensis_Diptera Habropoda_laboriosa_Hymenoptera Halyomorpha_halys_Hemiptera Harpegnathos_saltator_Hymenoptera Heliconius_cydno_hermogenes_Lepidoptera Heliconius_ethilla_aerotome_Lepidoptera Heliconius_hecale_felix_Lepidoptera Heliconius_ismenius_Lepidoptera Heliconius_melpomene_melpomene_Lepidoptera Hermetia_illucens_Diptera Drosophila_pseudoobscura_Diptera

# run 7
phyluce_probe_run_multiple_lastzs_sqlite --db run_7.sqlite --output run_7_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Holcocephala_fusca_Diptera Homalodisca_vitripennis_Hemiptera Hyalella_azteca_Curstacaea_Amphipoda Hypochthonius_rufulus_Chelicerata_Sarcoptiformes Hypothenemus_hampei_Coleoptera Isoperla_grammatica_Plecoptera Ixodes_ricinus_Chelicerata_Ixodida Ixodes_scapularis_Chelicerata_Ixodida Ladona_fulva_Odonata Lasioglossum_albipes_Hymenoptera Lasius_niger_Hymenoptera Latrodectus_hesperus_Chelicerata_Araneae

# run 8
phyluce_probe_run_multiple_lastzs_sqlite --db run_8.sqlite --output run_8_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Lepeophtheirus_salmonis_Curstacaea_Siphonostomatoida Leptinotarsa_decemlineata_Coleoptera Leptopilina_clavipes_Hymenoptera Lerema_accius_Lepidoptera Limnephilus_lunatus_Trichoptera Limulus_polyphemus_Chelicerata_Xiphosura Linepithema_humile_Hymenoptera Liriomyza_trifolii_Diptera Locusta_migratoria_Orthoptera Loxosceles_reclusa_Chelicerata_Araneae Lucilia_cuprina_Diptera Lucilia_sericata_Diptera Lutzomyia_longipalpis_Diptera Manduca_sexta_Lepidoptera Mayetiola_destructor_Diptera Megachile_rotundata_Hymenoptera Megaselia_abdita_Diptera Megaselia_scalaris_Diptera Melipona_quadrifasciata_Hymenoptera Melitaea_cinxia_Lepidoptera Mengenilla_moldrzyki_Strepsiptera Mesobuthus_martensii_Chelicerata_Scorpiones Microplitis_demolitor_Hymenoptera Mochlonyx_cinctipes_Diptera Monomorium_pharaonis_Hymenoptera Musca_domestica_Diptera Myzus_persicae_Hemiptera

# run 9
phyluce_probe_run_multiple_lastzs_sqlite --db run_9.sqlite --output run_9_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Nasonia_giraulti_Hymenoptera Nasonia_longicornis_Hymenoptera Nasonia_vitripennis_Hymenoptera Neobellieria_bullata_Diptera Neodiprion_lecontei_Hymenoptera Nicrophorus_vespilloides_Coleoptera Nilaparvata_lugens_Hemiptera Oncopeltus_fasciatus_Hemiptera Onthophagus_taurus_Coleoptera Operophtera_brumata_Lepidoptera Orchesella_cincta_Collembola Orussus_abietinus_Hymenoptera Oryctes_borbonicus_Coleoptera Pachypsylla_venusta_Hemiptera Papilio_glaucus_Lepidoptera Papilio_machaon_Lepidoptera Papilio_polytes_Lepidoptera Papilio_xuthus_Lepidoptera

# run 10
phyluce_probe_run_multiple_lastzs_sqlite --db run_10.sqlite --output run_10_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Parasteatoda_tepidariorum_Chelicerata_Araneae Parhyale_hawaiensis_Crustaceae_Amphipoda Pediculus_humanus_corporis_Phthiraptera Phlebotomus_papatasi_Diptera Phoebis_sennae_Lepidoptera Phormia_regina_Diptera Phortica_variegata_Diptera Pieris_rapae_Lepidoptera Platynothrus_peltifer_Chelicerata_Sarcoptiformes_Mite Plutella_xylostella_Lepidoptera Pogonomyrmex_barbatus_Hymenoptera Polistes_canadensis_Hymenoptera Polistes_dominula_Hymenoptera Proctacanthus_coquilletti_Diptera 

# run 11
phyluce_probe_run_multiple_lastzs_sqlite --db run_11.sqlite --output run_11_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Rhagoletis_zephyria_Diptera Rhipicephalus_microplus_Chelicerata_Ixodida Rhodnius_prolixus_Hemiptera Sarcophagidae_sp_BV2014_Diptera Sarcoptes_scabiei_Chelicerata_Sarcoptiformes_Mite Scaptodrosophila_lebanonensis_Diptera Solenopsis_invicta_Hymenoptera Sphyracephala_brevicornis_Diptera Spodoptera_frugiperda_Lepidoptera Steganacarus_magnus_Chelicerata_Oribatida Stegodyphus_mimosarum_Chelicerata_Araneae Stomoxys_calcitrans_Diptera Strigamia_maritima_Myriapoda Teleopsis_dalmanni_Diptera Tephritis_californica_Diptera 

# run 12
phyluce_probe_run_multiple_lastzs_sqlite --db run_12.sqlite --output run_12_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Tetranychus_urticae_Chelicerata_Trombidiformes Themira_minor_Diptera Tipula_oleracea_Diptera Trachymyrmex_cornetzi_Hymenoptera Trachymyrmex_septentrionalis_Hymenoptera Trachymyrmex_zeteki_Hymenoptera Tribolium_castaneum_Coleoptera Trichoceridae_sp_BV2014_Diptera Trichogramma_pretiosum_Hymenoptera Triops_cancriformis_Crustacaea_Notostraca Trupanea_jonesi_Diptera Varroa_destructor_Chelicerata_Parasitiformes Vollenhovia_emeryi_Hymenoptera Wasmannia_auropunctata_Hymenoptera Zaprionus_indianus_Diptera Zootermopsis_nevadensis_Isoptera

# run 13
phyluce_probe_run_multiple_lastzs_sqlite --db run_13.sqlite --output run_13_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist  Drosophila_willistoni_Diptera Drosophila_yakuba_Diptera Dufourea_novaeangliae_Hymenoptera Ephemera_danica_Ephemeroptera Ephydra_gracilis_Diptera Eristalis_dimidiata_Diptera Eufriesea_mexicana_Hymenoptera Eurytemora_affinis_Crustacaea_Calanoida Eutreta_diana_Diptera Fopius_arisanus_Hymenoptera Frankliniella_occidentalis_Thysanoptera Galendromus_occidentalis_Chelicerata_Mesostigmata Gerris_buenoi_Hemiptera Glossina_austeni_Diptera Glossina_brevipalpis_Diptera Glossina_fuscipes_fuscipes_Diptera Drosophila_albomicans_Diptera Drosophila_americana_Diptera Drosophila_ananassae_Diptera Drosophila_arizonae_Diptera Drosophila_biarmipes_Diptera Drosophila_bipectinata_Diptera

# run 14
phyluce_probe_run_multiple_lastzs_sqlite --db run_14.sqlite --output run_14_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Craig_Venter_Mammalia Mus_musculus_Mammalia Homo_sapiens_Mammalia Felis_catus_Mammalia

# run 15
phyluce_probe_run_multiple_lastzs_sqlite --db run_15.sqlite --output run_15_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Rattus_norvegicus_Mammalia Sus_scrofa_Mammalia Cavia_porcellus_Mammalia Ovis_aries_Mammalia

# run 16
phyluce_probe_run_multiple_lastzs_sqlite --db run_16.sqlite --output run_16_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Bos_taurus_Mammalia Equus_caballus_Mammalia Canus_lupus_Mammalia Chinchilla_lanigera_Mammalia

# run 17
phyluce_probe_run_multiple_lastzs_sqlite --db run_17.sqlite --output run_17_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Melampsora_larici_populina_98AG31 Punctularia_strigosozonata Stereum_hirsutum Tremella_mesenterica_DSM_1558 Dichomitus_squalens Heterobasidion_irregulare Wallemia_ichthyophaga Tilletiaria_anomala_UBC_951 Anthracocystis_flocculosa Phytophthora_ramorum Phytophthora_cinnamomi Pythium_aphanidermatum_DAOM_BR444 Albugo_candida Plasmopara_halstedii Pilasporangium_apinafurcum Hyaloperonospora_arabidopsidis Cladosporium_cladosporioides Cladosporium_sphaerospermum Cercospora_canescens Acremonium_chrysogenum Acremonium_furcatum Alternaria_brassicicola Alternaria_arborescens Aspergillus_nidulans_FGSC_A4 Aspergillus_terreus_NIH2624 Aspergillus_flavus_NRRL3357

# run 18
phyluce_probe_run_multiple_lastzs_sqlite --db run_18.sqlite --output run_18_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Aspergillus_clavatus_NRRL_1 Aspergillus_fischeri_NRRL_181 Fusarium_oxysporum_melonis Fusarium_graminearum Fusarium_fujikuroi Fusarium_virguliforme Fusarium_cuneirostrum Mortierella_alpina_ATCC_32222 Rhizopus_stolonifer_B9770 Mucor_velutinosus_B5328 Cunninghamella_bertholletiae_175 Umbelopsis_isabellina_B7317 Mucor_indicus_B7402 Saksenae_oblongispora_B3353 Mucor_ambiguus Choanephora_cucurbitarum Lichtheimia_corymbifera Stachybotrys_chartarum Memnoniella_echinata Trichoderma_reesei_QM6a Trichoderma_virens Trichoderma_atroviride_IMI_206040 Trichoderma_koningii Trichoderma_pleuroti Trichophyton_equinum Trichophyton_tonsurans_CBS_112818 Trichophyton_interdigitale_MR816 Trichophyton_violaceum Trichophyton_rubrum Starmerella_bombicola Candida_sp Candida_tropicalis Candida_albicans_CHN1 Clonostachys_rosea Coprinopsis_cinerea_okayama7130 Puccinia_graminis Schizophyllum_commune_H4 Malassezia_globosa_CBS_7966

# run 19
phyluce_probe_run_multiple_lastzs_sqlite --db run_19.sqlite --output run_19_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Pantoea_agglomerans Escherichia_coli Pseudomonas_oryzihabitans Sphingomonas_paucimobilis Staphylococcus_haemolyticus Staphylococcus_hominis Acinetobacter_lwoffii Klebsiella_pneumoniae Klebsiella_oxytoc Acinetobacter_baumannii Staphylococcus_aureus Salmonella_enterica Legionella_pneumophila Streptococcus_mitis Streptococcus_pneumoniae Clostridium_botulinum Clostridioides_difficile Bacillus_subtilis Methanobrevibacter_smithii Actinomyces_viscosus Lactobacillus_paracasei Fusobacterium_nucleatum Crocosphaera_watsonii Leucoagaricus_gongylophorus_Ac12 Leucoagaricus_sp_SymC_cos Propionibacterium_sp_oral_taxon_193 Propionibacterium_sp_5_U_42AFAA Propionibacterium_freudenreichii Propionibacterium_sp_KPL2000 Rhodococcus_pyridinivorans_SB3094 Rhodococcus_wratislaviensis Rhodococcus_maanshanensis_NBRC_100610 Rhodococcus_kroppenstedtii Rhodococcus_qingshengii Mycobacterium_marinum_E11 Mycobacterium_abscessus Mycobacterium_gilvum_Spyr1 Mycobacterium_colombiense Mycobacterium_chelonae_CCUG_47445 Mycobacterium_thermoresistibile Mycobacterium_xenopi_RIVM700367 Mycobacterium_mucogenicum Mycobacterium_holsaticum 

# run 20
phyluce_probe_run_multiple_lastzs_sqlite --db run_20.sqlite --output run_20_lastz --probefile ../../probesets/$(probefile) --genome-base-path ../../2bits/ --no-dir --coverage 80 --identity "${PWD##*_}" --cores $(corenumber) --scaffoldlist Mycobacterium_vulneris Mycobacterium_scrofulaceum Mycobacterium_neoaurum Mycobacterium_haemophilum Mycobacterium_smegmatis Mycobacterium_malmoense Mycobacterium_sinense Escherichia_coli_O157_H7_str_Sakai Escherichia_fergusonii Escherichia_albertii Atlantibacter_hermannii_NBRC_105704 Moraxella_osloensis Moraxella_macacae_0408225 Moraxella_atlantae Moraxella_bovoculi Moraxella_catarrhalis_103P14B1 Corynebacterium_amycolatum_SK46 Corynebacterium_resistens_DSM_45100 Corynebacterium_sp_ATCC_6931 Corynebacterium_pilosum_DSM_20521 Corynebacterium_maris_DSM_45190 Wolbachia_of_Drosophila_simulans Wolbachia_of_Nomada_panzeri Wolbachia_of_Nomada_ferruginata Wolbachia_of_Dactylopius_coccus Saccharomyces_cerevisiae Rhizophagus_irregularis Buchnera_aphidicola Candidatus_Hamiltonella_defensa Candidatus_Regiella_insecticola Serratia_symbiotica Spiroplasma_melliferum Arsenophonus_nasoniae Anaplasma_ovis Saprolegnia_diclina Wolbachia_pipientis Anncaliia_algerae Baeospora_myosura Amorphotheca_resinae
